---
#---------------- Chaincode Deployment---------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaincode-basic-org1
  labels:
    app: chaincode-basic-org1
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org1
    spec:
      containers:
        - image: mnaimhaziq/basic-cc-hlf:1.0
          imagePullPolicy: Always
          name: chaincode-basic-org1
          env:
            - name: CHAINCODE_ID
              value: "[1;30mnull[0m"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
