apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/
    server: 10.1.75.9
   